name: Update Weather

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get weather
        run: |
          curl "https://api.openweathermap.org/data/2.5/weather?q=Binh%20Duong&appid=${{ secrets.WEATHER_API_KEY }}&units=metric" > weather.json

      - name: Update README
        run: |
          TEMP=$(cat weather.json | jq '.main.temp')
          DESC=$(cat weather.json | jq -r '.weather[0].description')

          sed -i "s|<!-- WEATHER:START -->.*<!-- WEATHER:END -->|<!-- WEATHER:START --> 🌤 $TEMP°C - $DESC <!-- WEATHER:END -->|g" README.md

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update weather" || echo "No changes"
          git push
